import { execFileSync } from 'child_process';
import fs from 'fs';
import path from 'path';

const root = process.cwd();
const canonicalPath = path.join(
  root,
  'backend/sql/migrations/0003_memory_mirror_ingestion.sql',
);
const overlayPath = path.join(
  root,
  'backend/sql/overlays/supabase/0002_memory_mirror_ingestion.sql',
);
const generatedPath = path.join(
  root,
  'supabase/migrations/20260729062655_cloud_memory_phase_1_mirror.sql',
);
const generatorPath = path.join(
  root,
  'scripts/build-cloud-memory-phase1-migration.mjs',
);
const phase0GeneratedPath = path.join(
  root,
  'supabase/migrations/20260728144157_cloud_memory_foundation_20260728112723.sql',
);
const phase0FkGeneratedPath = path.join(
  root,
  'supabase/migrations/20260728144711_cloud_memory_fk_indexes_20260728145000.sql',
);

// Every new Phase 1 table from plan section 5.1, by exact name. The
// owner-current-source-set contract is implemented as additive columns on the
// Phase 0 memory_owner_state table, not as a new table.
const phase1Tables = [
  'memory_mirror_owner_allowlist',
  'memory_mirror_rate_limits',
  'memory_import_completion_permits',
  'memory_import_items',
  'memory_conversation_revisions',
];

// Every new Phase 1 SECURITY DEFINER service RPC from plan section 5.2.
const phase1Rpcs = [
  'memory_enroll_mirror_v1',
  'memory_reserve_mirror_request_v1',
  'memory_begin_source_import_v1',
  'memory_accept_source_chunk_v1',
  'memory_get_source_import_v1',
  'memory_cancel_source_import_v1',
  'memory_validate_source_import_v1',
  'memory_prepare_source_completion_v1',
  'memory_complete_source_import_v1',
  'memory_apply_source_tombstone_v1',
  'memory_get_source_parity_v1',
];

// Only mutations take the full Phase 0 deployment writer fence; the two GET
// RPCs are session-fenced reads.
const phase1Mutators = phase1Rpcs.filter((name) => ![
  'memory_get_source_import_v1',
  'memory_get_source_parity_v1',
].includes(name));
const phase1Readers = [
  'memory_get_source_import_v1',
  'memory_get_source_parity_v1',
];

function extractFunctionBody(sql, functionName) {
  const match = new RegExp(
    `create or replace function public\\.${functionName}\\([\\s\\S]*?`
    + 'as \\$\\$([\\s\\S]*?)\\$\\$;',
  ).exec(sql);
  return match?.[1] ?? null;
}

describe('cloud memory phase 1 migration contract', () => {
  it('is byte-generated exactly from canonical SQL and the Supabase overlay', () => {
    const canonical = fs.readFileSync(canonicalPath);
    const overlay = fs.readFileSync(overlayPath);
    const generated = fs.readFileSync(generatedPath);
    const header = Buffer.from(
      '-- GENERATED by scripts/build-cloud-memory-phase1-migration.mjs\n'
      + '-- Source: backend/sql/migrations/0003_memory_mirror_ingestion.sql\n'
      + '-- Overlay: backend/sql/overlays/supabase/0002_memory_mirror_ingestion.sql\n\n',
      'utf8',
    );

    expect(generated.equals(Buffer.concat([
      header,
      canonical,
      Buffer.from('\n'),
      overlay,
    ]))).toBe(true);
  });

  it('keeps the generated migration byte-current via the --check builder', () => {
    expect(() =>
      execFileSync(
        process.execPath,
        [generatorPath, '--check'],
        { cwd: root, stdio: 'pipe' },
      )
    ).not.toThrow();
  });

  it('uses a byte-preserving checkable generator', () => {
    const generator = fs.readFileSync(generatorPath, 'utf8');
    expect(generator).toContain("process.argv.includes('--check')");
    expect(generator).toContain('Buffer.concat');
    expect(generator).not.toContain('trim');
    expect(generator).toContain(
      'supabase/migrations/20260729062655_cloud_memory_phase_1_mirror.sql',
    );
    expect(generator).toContain(
      'backend/sql/migrations/0003_memory_mirror_ingestion.sql',
    );
    expect(generator).toContain(
      'backend/sql/overlays/supabase/0002_memory_mirror_ingestion.sql',
    );
  });

  it('uses LF-only byte-sensitive Phase 1 artifact lines in git attributes', () => {
    const gitAttributes = fs.readFileSync(path.join(root, '.gitattributes'), 'utf8');
    for (const byteSensitivePath of [
      'backend/sql/migrations/0003_memory_mirror_ingestion.sql',
      'backend/sql/overlays/supabase/0002_memory_mirror_ingestion.sql',
      'scripts/build-cloud-memory-phase1-migration.mjs',
      'supabase/migrations/20260729062655_cloud_memory_phase_1_mirror.sql',
    ]) {
      expect(gitAttributes).toContain(`${byteSensitivePath} text eol=lf`);
    }
  });

  it('never edits an applied Phase 0 migration or generated artifact', () => {
    const sql = fs.readFileSync(generatedPath, 'utf8').toLowerCase();
    expect(sql).not.toContain('drop table');
    // The Phase 0 artifacts stay byte-identical to their committed forms and
    // the historical placeholder remains empty.
    const phase0MigrationPath = path.join(
      root,
      'supabase/migrations/20260728112723_cloud_memory_foundation.sql',
    );
    expect(fs.readFileSync(phase0MigrationPath).length).toBe(0);
    expect(fs.readFileSync(phase0GeneratedPath).length).toBeGreaterThan(0);
    expect(fs.readFileSync(phase0FkGeneratedPath).length).toBeGreaterThan(0);
  });

  it('enumerates every new Phase 1 table from section 5.1 by name', () => {
    const sql = fs.readFileSync(canonicalPath, 'utf8');
    for (const table of phase1Tables) {
      expect(sql).toContain(`create table public.${table}`);
    }
  });

  it('creates only the new tables and rebuilds no Phase 0 table', () => {
    const sql = fs.readFileSync(canonicalPath, 'utf8');
    const creates = [...sql.matchAll(/create table public\.([a-z0-9_]+)/g)].map(
      (m) => m[1],
    );
    expect([...new Set(creates)].sort()).toEqual([...phase1Tables].sort());
    for (const phase0Table of [
      'memory_source_watermarks',
      'memory_evidence_spans',
      'memory_jobs',
      'memory_job_attempts',
      'turn_traces',
    ]) {
      expect(sql).not.toMatch(new RegExp(`create table public\\.${phase0Table}\\b`));
      expect(sql).not.toMatch(new RegExp(`alter table public\\.${phase0Table}\\b`));
    }
    // Additive-only evolution: ALTER is confined to exactly the Phase 0 tables
    // the plan's section 5.1 additive field / tombstone-receipt list owns, and
    // never drops a column.
    const altered = [...sql.matchAll(/alter table public\.([a-z0-9_]+)/g)].map(
      (m) => m[1],
    );
    expect([...new Set(altered)].sort()).toEqual([
      'memory_conversations',
      'memory_deletion_ledger',
      'memory_import_chunks',
      'memory_import_manifests',
      'memory_message_revisions',
      'memory_messages',
      'memory_owner_state',
    ]);
    expect(sql).not.toMatch(/drop column|drop table|truncate/i);
    // The additive fields the plan requires are present, with the positive
    // mirror source revision and staged/eligible/deleted eligibility language.
    expect(sql).toContain('eligibility');
    expect(sql).toContain('source_revision');
    expect(sql).toContain(`'staged', 'eligible', 'deleted'`);
    expect(sql).toContain('first_observed');
    expect(sql).toContain('coalesced_gap');
    expect(sql).toContain('revision_provenance');
  });

  it('never extends memory_source_watermarks (section 4.2 mirror sequencing)', () => {
    const stripComments = (text: string) =>
      text.split('\n').map((l) => l.replace(/--.*$/, '')).join('\n').toLowerCase();
    const sql = stripComments(fs.readFileSync(canonicalPath, 'utf8'));
    // The Phase 0 table is not created, not altered, and not referenced by any
    // executable mirror RPC. It is reused only by the legacy
    // EXPO_PUBLIC_DATA_PROVIDER path which lives outside this migration.
    expect(sql).not.toContain('memory_source_watermarks');
    const overlay = stripComments(fs.readFileSync(overlayPath, 'utf8'));
    expect(overlay).not.toContain('memory_source_watermarks');
  });

  it('keeps provider primitives out of canonical SQL and fences every mutator', () => {
    const sql = fs.readFileSync(canonicalPath, 'utf8').toLowerCase();
    expect(sql).not.toContain('auth.uid()');
    expect(sql).not.toMatch(/\b(service_role|authenticated|anon)\b/);
    expect(sql).toContain('for update skip locked');
    expect(sql).toContain('for share');
    expect(sql).toContain('clock_timestamp()');
    expect(sql).toContain('set search_path = \'\'');
    // Phase 1 mutators rely on the Phase 0 fenced writer assertion rather than
    // re-declaring its fence fields.
    expect(sql).not.toContain('is distinct from p_writer_epoch');
    expect(sql).not.toContain('is distinct from p_deployment_id');

    for (const functionName of phase1Mutators) {
      const body = extractFunctionBody(
        fs.readFileSync(canonicalPath, 'utf8'),
        functionName,
      );
      expect({ name: functionName, missing: body === null }).toEqual({
        name: functionName,
        missing: false,
      });
      expect({
        name: functionName,
        fenced: body?.includes('perform public.memory_assert_writer(') ?? false,
      }).toEqual({ name: functionName, fenced: true });
    }
    for (const functionName of phase1Readers) {
      const body = extractFunctionBody(
        fs.readFileSync(canonicalPath, 'utf8'),
        functionName,
      );
      expect({ name: functionName, missing: body === null }).toEqual({
        name: functionName,
        missing: false,
      });
      expect({
        name: functionName,
        fenced: body?.includes('memory_assert_mirror_owner_access(') ?? false,
      }).toEqual({ name: functionName, fenced: true });
    }
  });

  it('keeps runtime mutation RPC-only and service_role-only in the overlay', () => {
    const sql = fs.readFileSync(overlayPath, 'utf8').toLowerCase();
    expect(sql).toContain('force row level security');
    expect(sql).not.toMatch(/grant\s+all\s+on\s+table[\s\S]*\bto\s+service_role\b/);
    expect(sql).toMatch(
      /revoke\s+all\s+on\s+table[\s\S]*from\s+public,\s*anon,\s*authenticated,\s*service_role/,
    );

    for (const functionName of phase1Rpcs) {
      expect(sql).toContain(`revoke all on function public.${functionName}`);
      expect(sql).toContain(`grant execute on function public.${functionName}`);
    }
    expect(sql).not.toMatch(/grant\s+execute[\s\S]*\bto\s+(anon|authenticated)\b/);
  });
});
