import fs from 'fs';
import path from 'path';

const root = process.cwd();
const canonicalPath = path.join(
  root,
  'backend/sql/migrations/0001_memory_foundation.sql',
);
const overlayPath = path.join(
  root,
  'backend/sql/overlays/supabase/0001_memory_foundation.sql',
);
const generatedPath = path.join(
  root,
  'supabase/migrations/20260728112723_cloud_memory_foundation.sql',
);
const generatorPath = path.join(root, 'scripts/build-cloud-memory-migration.mjs');
const fkIndexCanonicalPath = path.join(
  root,
  'backend/sql/migrations/0002_memory_fk_indexes.sql',
);
const fkIndexSupabasePath = path.join(
  root,
  'supabase/migrations/20260728145000_cloud_memory_fk_indexes.sql',
);

describe('cloud memory migration contract', () => {
  it('is byte-generated exactly from canonical SQL and the Supabase overlay', () => {
    const canonical = fs.readFileSync(canonicalPath);
    const overlay = fs.readFileSync(overlayPath);
    const generated = fs.readFileSync(generatedPath);
    const header = Buffer.from(
      '-- GENERATED by scripts/build-cloud-memory-migration.mjs\n'
      + '-- Source: backend/sql/migrations/0001_memory_foundation.sql\n'
      + '-- Overlay: backend/sql/overlays/supabase/0001_memory_foundation.sql\n\n',
      'utf8',
    );

    expect(generated.equals(Buffer.concat([
      header,
      canonical,
      Buffer.from('\n'),
      overlay,
    ]))).toBe(true);
  });

  it('keeps provider primitives out of canonical SQL and fences every mutator', () => {
    const sql = fs.readFileSync(canonicalPath, 'utf8').toLowerCase();
    expect(sql).not.toContain('auth.uid()');
    expect(sql).not.toMatch(/\b(service_role|authenticated|anon)\b/);
    expect(sql).not.toContain('jsonb_object_length');
    expect(sql).toContain('for update skip locked');
    expect(sql).toContain('for share');
    expect(sql).toContain('is distinct from p_writer_epoch');
    expect(sql).toContain('is distinct from p_deployment_id');
    expect(sql).toContain('clock_timestamp()');
    expect(sql).toContain('memory_idempotency_conflict');
    expect(sql).toContain('memory_source_watermark_conflict');
    expect(sql).toContain('job_lease_expired');
    expect(sql).toContain('on delete set null (conversation_id)');
    expect(sql).toContain('on delete set null (created_by_job_id)');

    for (const functionName of [
      'memory_begin_import',
      'memory_accept_import_chunk',
      'memory_record_deletion',
      'memory_enqueue_job',
      'memory_claim_jobs',
      'memory_finish_job',
    ]) {
      const body = new RegExp(
        `create or replace function public\\.${functionName}\\([\\s\\S]*?`
        + 'as \\$\\$([\\s\\S]*?)\\$\\$;',
      ).exec(sql)?.[1];
      expect(body).toContain('perform public.memory_assert_writer(');
    }
  });

  it('pins the strict flag, epoch, job type, deletion, and claim contracts', () => {
    const sql = fs.readFileSync(canonicalPath, 'utf8').toLowerCase();
    for (const flag of [
      'cloudsourcemirroring',
      'cloudprojectionbuild',
      'shadowretrieval',
      'cloudreadauthority',
      'cloudwriteauthority',
    ]) {
      expect(sql).toContain(`jsonb_typeof(feature_flags->'${flag}') = 'boolean'`);
    }
    expect(sql).toContain('writer_epoch between 1 and 9007199254740991');
    expect(sql).toContain('authority_version between 1 and 9007199254740991');
    expect(sql).toContain("'verify_deletion'");
    expect(sql).toContain('memory_jobs_claim_ready_idx');
    expect(sql).toContain('memory_jobs_claim_expired_idx');
    expect(sql).toContain('verification_status = \'verified\' and verified_at is not null');
  });

  it('keeps runtime mutation RPC-only in the Supabase overlay', () => {
    const sql = fs.readFileSync(overlayPath, 'utf8').toLowerCase();
    expect(sql).toContain('force row level security');
    expect(sql).not.toMatch(/grant\s+all\s+on\s+table[\s\S]*\bto\s+service_role\b/);
    expect(sql).toMatch(
      /revoke\s+all\s+on\s+table[\s\S]*from\s+public,\s*anon,\s*authenticated,\s*service_role/,
    );

    for (const functionName of [
      'memory_begin_import',
      'memory_accept_import_chunk',
      'memory_record_deletion',
      'memory_enqueue_job',
      'memory_claim_jobs',
      'memory_finish_job',
      'memory_get_bootstrap',
      'memory_get_owner_state',
      'memory_get_source_inventory',
    ]) {
      expect(sql).toContain(`revoke all on function public.${functionName}`);
      expect(sql).toContain(`grant execute on function public.${functionName}`);
    }
    expect(sql).not.toMatch(/grant\s+execute[\s\S]*\bto\s+(anon|authenticated)\b/);
  });

  it('uses a byte-preserving checkable generator and PostgreSQL 17 config', () => {
    const generator = fs.readFileSync(generatorPath, 'utf8');
    const config = fs.readFileSync(
      path.join(root, 'supabase/config.toml'),
      'utf8',
    );
    const localIgnore = fs.readFileSync(
      path.join(root, 'supabase/.gitignore'),
      'utf8',
    );
    const gitAttributes = fs.readFileSync(
      path.join(root, '.gitattributes'),
      'utf8',
    );

    expect(generator).toContain("process.argv.includes('--check')");
    expect(generator).toContain('Buffer.concat');
    expect(generator).not.toContain('trim');
    expect(config).toMatch(/\[db\][\s\S]*major_version\s*=\s*17/);
    expect(localIgnore).toContain('.branches');
    expect(localIgnore).toContain('.temp');
    for (const byteSensitivePath of [
      'backend/sql/migrations/0001_memory_foundation.sql',
      'backend/sql/overlays/supabase/0001_memory_foundation.sql',
      'scripts/build-cloud-memory-migration.mjs',
      'supabase/migrations/20260728112723_cloud_memory_foundation.sql',
    ]) {
      expect(gitAttributes).toContain(`${byteSensitivePath} text eol=lf`);
    }
  });

  it('keeps the additive foreign-key index migration provider-neutral', () => {
    const canonical = fs.readFileSync(fkIndexCanonicalPath);
    const supabaseMigration = fs.readFileSync(fkIndexSupabasePath);
    expect(supabaseMigration.equals(canonical)).toBe(true);

    const sql = canonical.toString('utf8').toLowerCase();
    expect(sql).toContain('memory_evidence_spans_created_by_job_idx');
    expect(sql).toContain('memory_evidence_spans (owner_id, created_by_job_id)');
    expect(sql).toContain('turn_traces_conversation_idx');
    expect(sql).toContain('turn_traces (owner_id, conversation_id)');
    expect(sql).not.toMatch(/\b(auth|anon|authenticated|service_role)\b/);
  });
});
