-- GENERATED by scripts/build-cloud-memory-migration.mjs
-- Source: backend/sql/migrations/0001_memory_foundation.sql
-- Overlay: backend/sql/overlays/supabase/0001_memory_foundation.sql

create table public.memory_deployment_authority (
  singleton boolean primary key default true check (singleton),
  deployment_id text not null
    check (deployment_id ~ '^[A-Za-z0-9][A-Za-z0-9._-]*$'),
  writer_epoch bigint not null
    check (writer_epoch between 1 and 9007199254740991),
  mode text not null
    check (mode in ('active', 'maintenance', 'read_only', 'retired')),
  backend_base_url text,
  database_fingerprint text not null
    check (database_fingerprint ~ '^sha256:[A-Za-z0-9][A-Za-z0-9._-]*$'),
  writer_lease_id uuid,
  writer_lease_token_digest text
    check (
      writer_lease_token_digest is null
      or writer_lease_token_digest ~ '^[0-9a-f]{64}$'
    ),
  writer_lease_expires_at timestamptz,
  writer_lease_issuer text
    check (
      writer_lease_issuer is null
      or writer_lease_issuer ~ '^[A-Za-z0-9][A-Za-z0-9._-]*$'
    ),
  writer_lease_key_id text
    check (
      writer_lease_key_id is null
      or writer_lease_key_id ~ '^[A-Za-z0-9][A-Za-z0-9._-]*$'
    ),
  source_credential_fingerprint text
    check (
      source_credential_fingerprint is null
      or source_credential_fingerprint
        ~ '^sha256:[A-Za-z0-9][A-Za-z0-9._-]*$'
    ),
  changed_at timestamptz not null default now(),
  change_reason text not null check (btrim(change_reason) <> ''),
  check (
    mode <> 'active'
    or (
      writer_lease_id is not null
      and writer_lease_token_digest is not null
      and writer_lease_expires_at is not null
      and writer_lease_issuer is not null
      and writer_lease_key_id is not null
      and source_credential_fingerprint is not null
    )
  )
);

insert into public.memory_deployment_authority (
  singleton,
  deployment_id,
  writer_epoch,
  mode,
  database_fingerprint,
  change_reason
) values (
  true,
  'blackrose-primary',
  1,
  'maintenance',
  'sha256:phase0-unprovisioned',
  'phase-0 bootstrap; replace fingerprint before hosted writes'
);

create table public.memory_owner_state (
  owner_id uuid primary key,
  authority_state text not null default 'LOCAL'
    check (authority_state in ('LOCAL', 'MIRROR', 'SHADOW', 'CLOUD')),
  authority_version bigint not null default 1
    check (authority_version between 1 and 9007199254740991),
  feature_flags jsonb not null default '{
    "cloudSourceMirroring": false,
    "cloudProjectionBuild": false,
    "shadowRetrieval": false,
    "cloudReadAuthority": false,
    "cloudWriteAuthority": false
  }'::jsonb,
  observation_started_at timestamptz,
  updated_at timestamptz not null default now(),
  check (
    jsonb_typeof(feature_flags) = 'object'
    and feature_flags ?& array[
      'cloudSourceMirroring',
      'cloudProjectionBuild',
      'shadowRetrieval',
      'cloudReadAuthority',
      'cloudWriteAuthority'
    ]::text[]
    and (
      feature_flags - array[
        'cloudSourceMirroring',
        'cloudProjectionBuild',
        'shadowRetrieval',
        'cloudReadAuthority',
        'cloudWriteAuthority'
      ]::text[]
    ) = '{}'::jsonb
    and jsonb_typeof(feature_flags->'cloudSourceMirroring') = 'boolean'
    and jsonb_typeof(feature_flags->'cloudProjectionBuild') = 'boolean'
    and jsonb_typeof(feature_flags->'shadowRetrieval') = 'boolean'
    and jsonb_typeof(feature_flags->'cloudReadAuthority') = 'boolean'
    and jsonb_typeof(feature_flags->'cloudWriteAuthority') = 'boolean'
  )
);

create table public.memory_source_watermarks (
  owner_id uuid not null,
  source_kind text not null
    check (source_kind in ('journal', 'freeform_chat', 'intention_checkin')),
  highest_client_sequence bigint not null default 0
    check (highest_client_sequence >= 0),
  highest_client_event_id text,
  observed_at timestamptz not null,
  updated_at timestamptz not null default now(),
  primary key (owner_id, source_kind)
);

create table public.memory_deletion_ledger (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null,
  source_kind text not null
    check (source_kind in ('journal', 'freeform_chat', 'intention_checkin')),
  source_id text not null,
  source_revision integer not null check (source_revision > 0),
  client_event_id text not null,
  deleted_at timestamptz not null,
  reason_code text not null,
  verification_status text not null default 'pending'
    check (verification_status in ('pending', 'verified', 'failed')),
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  unique (owner_id, client_event_id),
  unique (owner_id, source_kind, source_id, source_revision),
  check (
    (verification_status = 'verified' and verified_at is not null)
    or (verification_status <> 'verified' and verified_at is null)
  )
);

create table public.memory_conversations (
  id text not null,
  owner_id uuid not null,
  source_kind text not null
    check (source_kind in ('journal', 'freeform_chat', 'intention_checkin')),
  source_record_id text not null,
  status text not null
    check (status in ('draft', 'active', 'settled', 'deleted')),
  started_at timestamptz not null,
  settled_at timestamptz,
  timezone text,
  week_starts_on smallint check (week_starts_on in (0, 1)),
  temporal_provenance text not null
    check (temporal_provenance in ('captured', 'legacy_unknown')),
  client_schema_version integer not null check (client_schema_version > 0),
  source_hash text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (owner_id, id),
  unique (owner_id, source_kind, source_record_id),
  check (
    temporal_provenance = 'captured'
    or (timezone is null and week_starts_on is null and settled_at is null)
  )
);

create table public.memory_messages (
  id text not null,
  owner_id uuid not null,
  conversation_id text not null,
  client_event_id text not null,
  role text not null check (role in ('user', 'assistant', 'system', 'tool')),
  sequence integer not null check (sequence >= 0),
  authored_at timestamptz not null,
  authored_timezone text,
  local_date date,
  temporal_provenance text not null
    check (temporal_provenance in ('captured', 'legacy_unknown')),
  content text not null,
  content_hash text,
  revision integer not null default 1 check (revision > 0),
  status text not null default 'active'
    check (status in ('active', 'edited', 'deleted')),
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (owner_id, id),
  unique (owner_id, client_event_id),
  unique (owner_id, conversation_id, sequence),
  foreign key (owner_id, conversation_id)
    references public.memory_conversations (owner_id, id) on delete cascade,
  check (
    temporal_provenance = 'captured'
    or (authored_timezone is null and local_date is null)
  )
);

create table public.memory_message_revisions (
  id bigint generated always as identity primary key,
  owner_id uuid not null,
  message_id text not null,
  revision integer not null check (revision > 0),
  content text not null,
  content_hash text,
  authored_at timestamptz not null,
  authored_timezone text,
  local_date date,
  temporal_provenance text not null
    check (temporal_provenance in ('captured', 'legacy_unknown')),
  lifecycle_reason text not null,
  eligibility text not null
    check (eligibility in ('eligible', 'withheld', 'deleted', 'expired')),
  created_at timestamptz not null default now(),
  unique (owner_id, id),
  unique (owner_id, message_id, revision),
  foreign key (owner_id, message_id)
    references public.memory_messages (owner_id, id) on delete cascade
);

create table public.memory_jobs (
  id bigint generated always as identity primary key,
  owner_id uuid not null,
  job_type text not null check (job_type in (
    'capture_source',
    'extract_turn_candidates',
    'checkpoint_conversation',
    'curate_session',
    'reconcile_entities',
    'reconcile_claims',
    'audit_epistemic_authorization',
    'audit_supersession_chains',
    'build_temporal_digest',
    'build_current_life_snapshot',
    'build_profile_tree',
    'build_search_document',
    'embed_search_document',
    'observe_interaction_outcome',
    'review_pattern_hypotheses',
    'scan_cross_domain_collisions',
    'rebuild_personalized_promotion_policy',
    'refresh_external_fact_snapshot',
    'cascade_source_invalidation',
    'verify_deletion',
    'compare_shadow_retrieval',
    'rebuild_projection_version'
  )),
  idempotency_key text not null,
  source_version text not null,
  payload_reference jsonb not null default '{}'::jsonb
    check (jsonb_typeof(payload_reference) = 'object'),
  status text not null default 'queued'
    check (
      status in (
        'queued',
        'leased',
        'succeeded',
        'retryable',
        'dead_letter',
        'cancelled'
      )
    ),
  priority smallint not null default 0,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  max_attempts integer not null default 5 check (max_attempts > 0),
  available_at timestamptz not null default now(),
  lease_started_at timestamptz,
  lease_expires_at timestamptz,
  worker_id text,
  lease_token uuid,
  last_error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (owner_id, id),
  unique (owner_id, job_type, idempotency_key, source_version),
  check (
    status <> 'leased'
    or (
      worker_id is not null
      and btrim(worker_id) <> ''
      and lease_token is not null
      and lease_started_at is not null
      and lease_expires_at is not null
      and lease_expires_at > lease_started_at
    )
  )
);

create table public.memory_evidence_spans (
  id bigint generated always as identity primary key,
  owner_id uuid not null,
  message_revision_id bigint not null,
  start_offset integer not null check (start_offset >= 0),
  end_offset integer not null check (end_offset > start_offset),
  span_hash text not null,
  evidence_kind text not null,
  eligibility text not null
    check (eligibility in ('eligible', 'withheld', 'deleted', 'expired')),
  created_by_job_id bigint,
  created_at timestamptz not null default now(),
  unique (owner_id, id),
  unique (owner_id, message_revision_id, start_offset, end_offset),
  foreign key (owner_id, message_revision_id)
    references public.memory_message_revisions (owner_id, id) on delete cascade,
  foreign key (owner_id, created_by_job_id)
    references public.memory_jobs (owner_id, id)
    on delete set null (created_by_job_id)
);

create table public.memory_job_attempts (
  id bigint generated always as identity primary key,
  owner_id uuid not null,
  job_id bigint not null,
  attempt_number integer not null check (attempt_number > 0),
  lease_token uuid not null,
  worker_id text not null check (btrim(worker_id) <> ''),
  provider text,
  model text,
  token_usage jsonb not null default '{}'::jsonb
    check (jsonb_typeof(token_usage) = 'object'),
  status_code integer,
  schema_version integer not null check (schema_version > 0),
  started_at timestamptz not null,
  finished_at timestamptz not null,
  outcome text not null
    check (outcome in ('succeeded', 'retryable', 'dead_letter', 'cancelled')),
  error_code text,
  redacted_diagnostics jsonb not null default '{}'::jsonb
    check (jsonb_typeof(redacted_diagnostics) = 'object'),
  duration_ms integer not null check (duration_ms >= 0),
  unique (owner_id, job_id, attempt_number),
  foreign key (owner_id, job_id)
    references public.memory_jobs (owner_id, id) on delete cascade
);

create table public.memory_import_manifests (
  id text not null,
  owner_id uuid not null,
  contract_version integer not null check (contract_version > 0),
  source_count integer not null check (source_count >= 0),
  message_count integer not null check (message_count >= 0),
  source_hash text,
  status text not null
    check (status in ('created', 'uploading', 'verified', 'failed', 'cancelled')),
  created_at timestamptz not null default now(),
  verified_at timestamptz,
  primary key (owner_id, id)
);

create table public.memory_import_chunks (
  id bigint generated always as identity primary key,
  owner_id uuid not null,
  manifest_id text not null,
  chunk_index integer not null check (chunk_index >= 0),
  idempotency_key text not null,
  item_count integer not null check (item_count >= 0),
  chunk_hash text not null,
  source_kind text not null
    check (source_kind in ('journal', 'freeform_chat', 'intention_checkin')),
  highest_client_sequence bigint not null check (highest_client_sequence >= 0),
  highest_client_event_id text,
  observed_at timestamptz not null,
  status text not null check (status in ('accepted', 'verified', 'failed')),
  accepted_at timestamptz not null default now(),
  unique (owner_id, id),
  unique (owner_id, manifest_id, chunk_index),
  unique (owner_id, idempotency_key),
  foreign key (owner_id, manifest_id)
    references public.memory_import_manifests (owner_id, id) on delete cascade
);

create table public.turn_traces (
  id text not null,
  owner_id uuid not null,
  conversation_id text,
  authority_state text not null
    check (authority_state in ('LOCAL', 'MIRROR', 'SHADOW', 'CLOUD')),
  source_turn_ids jsonb not null default '[]'::jsonb,
  route text not null,
  reason_codes jsonb not null default '[]'::jsonb,
  status text not null,
  model_versions jsonb not null default '{}'::jsonb,
  prompt_versions jsonb not null default '{}'::jsonb,
  retrieval_evidence_ids jsonb not null default '[]'::jsonb,
  target_count integer not null default 0 check (target_count >= 0),
  covered_target_count integer not null default 0
    check (covered_target_count >= 0),
  expansion_cycles integer not null default 0 check (expansion_cycles >= 0),
  stop_reason text,
  token_usage jsonb not null default '{}'::jsonb,
  latency_ms jsonb not null default '{}'::jsonb,
  cost_microusd bigint not null default 0 check (cost_microusd >= 0),
  response_hash text,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  primary key (owner_id, id),
  foreign key (owner_id, conversation_id)
    references public.memory_conversations (owner_id, id)
    on delete set null (conversation_id)
);

create index memory_conversations_owner_started_idx
  on public.memory_conversations (owner_id, started_at desc);
create index memory_source_watermarks_owner_updated_idx
  on public.memory_source_watermarks (owner_id, updated_at desc);
create index memory_deletion_ledger_owner_deleted_idx
  on public.memory_deletion_ledger (owner_id, deleted_at desc);
create index memory_deletion_pending_idx
  on public.memory_deletion_ledger (created_at, id)
  where verification_status = 'pending';
create index memory_messages_owner_authored_idx
  on public.memory_messages (owner_id, authored_at);
create index memory_jobs_claim_ready_idx
  on public.memory_jobs (priority desc, available_at, created_at, id)
  where status in ('queued', 'retryable');
create index memory_jobs_claim_expired_idx
  on public.memory_jobs (lease_expires_at, priority desc, available_at, created_at, id)
  where status = 'leased';
create index memory_import_manifests_owner_created_idx
  on public.memory_import_manifests (owner_id, created_at desc);
create index turn_traces_owner_created_idx
  on public.turn_traces (owner_id, created_at desc);

create or replace function public.memory_assert_writer(
  p_deployment_id text,
  p_writer_epoch bigint,
  p_writer_lease_id uuid,
  p_writer_lease_token text,
  p_source_credential_fingerprint text
) returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  authority public.memory_deployment_authority%rowtype;
begin
  select *
  into authority
  from public.memory_deployment_authority
  where singleton = true
  for share;

  if not found then
    raise exception using
      errcode = 'P0001',
      message = 'MEMORY_AUTHORITY_UNAVAILABLE';
  end if;
  if authority.mode <> 'active' then
    raise exception using errcode = 'P0001', message = 'MEMORY_WRITES_DISABLED';
  end if;
  if authority.deployment_id is distinct from p_deployment_id then
    raise exception using
      errcode = 'P0001',
      message = 'MEMORY_DEPLOYMENT_MISMATCH';
  end if;
  if authority.writer_epoch is distinct from p_writer_epoch then
    raise exception using
      errcode = 'P0001',
      message = 'MEMORY_STALE_WRITER_EPOCH';
  end if;
  if authority.writer_lease_id is distinct from p_writer_lease_id then
    raise exception using
      errcode = 'P0001',
      message = 'MEMORY_WRITER_LEASE_MISMATCH';
  end if;
  if authority.writer_lease_expires_at is null
      or authority.writer_lease_expires_at <= clock_timestamp() then
    raise exception using
      errcode = 'P0001',
      message = 'MEMORY_WRITER_LEASE_EXPIRED';
  end if;
  if p_writer_lease_token is null or btrim(p_writer_lease_token) = '' then
    raise exception using
      errcode = 'P0001',
      message = 'MEMORY_WRITER_LEASE_TOKEN_INVALID';
  end if;
  if authority.writer_lease_token_digest is distinct from encode(
    sha256(convert_to(p_writer_lease_token, 'UTF8')),
    'hex'
  ) then
    raise exception using
      errcode = 'P0001',
      message = 'MEMORY_WRITER_LEASE_TOKEN_INVALID';
  end if;
  if authority.source_credential_fingerprint
      is distinct from p_source_credential_fingerprint then
    raise exception using
      errcode = 'P0001',
      message = 'MEMORY_SOURCE_CREDENTIAL_MISMATCH';
  end if;
end;
$$;

create or replace function public.memory_enqueue_job(
  p_deployment_id text,
  p_writer_epoch bigint,
  p_writer_lease_id uuid,
  p_writer_lease_token text,
  p_source_credential_fingerprint text,
  p_owner_id uuid,
  p_job_type text,
  p_idempotency_key text,
  p_source_version text,
  p_payload_reference jsonb,
  p_priority integer default 0,
  p_max_attempts integer default 5
) returns public.memory_jobs
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.memory_jobs%rowtype;
begin
  perform public.memory_assert_writer(
    p_deployment_id,
    p_writer_epoch,
    p_writer_lease_id,
    p_writer_lease_token,
    p_source_credential_fingerprint
  );

  insert into public.memory_jobs (
    owner_id,
    job_type,
    idempotency_key,
    source_version,
    payload_reference,
    priority,
    max_attempts
  ) values (
    p_owner_id,
    p_job_type,
    p_idempotency_key,
    p_source_version,
    coalesce(p_payload_reference, '{}'::jsonb),
    coalesce(p_priority, 0),
    coalesce(p_max_attempts, 5)
  )
  on conflict (owner_id, job_type, idempotency_key, source_version)
  do nothing
  returning * into result;

  if not found then
    select *
    into result
    from public.memory_jobs
    where owner_id = p_owner_id
      and job_type = p_job_type
      and idempotency_key = p_idempotency_key
      and source_version = p_source_version
    for update;

    if not found
        or result.payload_reference
          is distinct from coalesce(p_payload_reference, '{}'::jsonb)
        or result.priority is distinct from coalesce(p_priority, 0)
        or result.max_attempts is distinct from coalesce(p_max_attempts, 5) then
      raise exception using
        errcode = 'PT409',
        message = 'MEMORY_IDEMPOTENCY_CONFLICT';
    end if;
  end if;

  return result;
end;
$$;

create or replace function public.memory_claim_jobs(
  p_deployment_id text,
  p_writer_epoch bigint,
  p_writer_lease_id uuid,
  p_writer_lease_token text,
  p_source_credential_fingerprint text,
  p_worker_id text,
  p_limit integer default 10,
  p_lease_seconds integer default 60
) returns setof public.memory_jobs
language plpgsql
security definer
set search_path = ''
as $$
declare
  exhausted public.memory_jobs%rowtype;
begin
  perform public.memory_assert_writer(
    p_deployment_id,
    p_writer_epoch,
    p_writer_lease_id,
    p_writer_lease_token,
    p_source_credential_fingerprint
  );

  if p_worker_id is null or btrim(p_worker_id) = '' then
    raise exception using errcode = '22023', message = 'MEMORY_WORKER_ID_INVALID';
  end if;

  for exhausted in
    select *
    from public.memory_jobs
    where status in ('queued', 'retryable', 'leased')
      and attempt_count >= max_attempts
      and (status <> 'leased' or lease_expires_at <= clock_timestamp())
    for update skip locked
  loop
    if exhausted.status = 'leased' then
      insert into public.memory_job_attempts (
        owner_id,
        job_id,
        attempt_number,
        lease_token,
        worker_id,
        token_usage,
        schema_version,
        started_at,
        finished_at,
        outcome,
        error_code,
        redacted_diagnostics,
        duration_ms
      ) values (
        exhausted.owner_id,
        exhausted.id,
        exhausted.attempt_count,
        exhausted.lease_token,
        exhausted.worker_id,
        '{}'::jsonb,
        1,
        exhausted.lease_started_at,
        clock_timestamp(),
        'dead_letter',
        'JOB_LEASE_EXPIRED',
        '{}'::jsonb,
        least(
          2147483647,
          greatest(
            0,
            floor(
              extract(epoch from (
                clock_timestamp() - exhausted.lease_started_at
              )) * 1000
            )
          )
        )::integer
      )
      on conflict (owner_id, job_id, attempt_number) do nothing;
    end if;

    update public.memory_jobs
    set status = 'dead_letter',
        completed_at = clock_timestamp(),
        updated_at = clock_timestamp(),
        last_error_code = coalesce(last_error_code, 'MAX_ATTEMPTS_EXHAUSTED'),
        worker_id = null,
        lease_token = null,
        lease_started_at = null,
        lease_expires_at = null
    where id = exhausted.id;
  end loop;

  return query
  with candidates as materialized (
    select job.*
    from public.memory_jobs as job
    where (
      job.status in ('queued', 'retryable')
      or (
        job.status = 'leased'
        and job.lease_expires_at <= clock_timestamp()
      )
    )
      and job.available_at <= clock_timestamp()
      and job.attempt_count < job.max_attempts
    order by job.priority desc, job.available_at, job.created_at, job.id
    limit greatest(1, least(coalesce(p_limit, 10), 50))
    for update skip locked
  ),
  expired_attempts as (
    insert into public.memory_job_attempts (
      owner_id,
      job_id,
      attempt_number,
      lease_token,
      worker_id,
      token_usage,
      schema_version,
      started_at,
      finished_at,
      outcome,
      error_code,
      redacted_diagnostics,
      duration_ms
    )
    select
      owner_id,
      id,
      attempt_count,
      lease_token,
      worker_id,
      '{}'::jsonb,
      1,
      lease_started_at,
      clock_timestamp(),
      'retryable',
      'JOB_LEASE_EXPIRED',
      '{}'::jsonb,
      least(
        2147483647,
        greatest(
          0,
          floor(
            extract(epoch from (clock_timestamp() - lease_started_at)) * 1000
          )
        )
      )::integer
    from candidates
    where status = 'leased'
    on conflict (owner_id, job_id, attempt_number) do nothing
    returning job_id
  ),
  expired_attempt_count as (
    select count(*) from expired_attempts
  )
  update public.memory_jobs as job
  set status = 'leased',
      worker_id = p_worker_id,
      lease_token = gen_random_uuid(),
      lease_started_at = clock_timestamp(),
      lease_expires_at = clock_timestamp() + make_interval(
        secs => greatest(15, least(coalesce(p_lease_seconds, 60), 900))
      ),
      attempt_count = job.attempt_count + 1,
      updated_at = clock_timestamp()
  from candidates, expired_attempt_count
  where job.id = candidates.id
  returning job.*;
end;
$$;

create or replace function public.memory_finish_job(
  p_deployment_id text,
  p_writer_epoch bigint,
  p_writer_lease_id uuid,
  p_writer_lease_token text,
  p_source_credential_fingerprint text,
  p_job_id bigint,
  p_worker_id text,
  p_lease_token uuid,
  p_outcome text,
  p_error_code text default null,
  p_retry_delay_seconds integer default 15,
  p_provider text default null,
  p_model text default null,
  p_token_usage jsonb default '{}'::jsonb,
  p_status_code integer default null,
  p_schema_version integer default 1,
  p_started_at timestamptz default null,
  p_redacted_diagnostics jsonb default '{}'::jsonb
) returns public.memory_jobs
language plpgsql
security definer
set search_path = ''
as $$
declare
  job public.memory_jobs%rowtype;
  final_outcome text;
  attempt_started_at timestamptz;
begin
  perform public.memory_assert_writer(
    p_deployment_id,
    p_writer_epoch,
    p_writer_lease_id,
    p_writer_lease_token,
    p_source_credential_fingerprint
  );

  if p_outcome not in ('succeeded', 'retryable', 'dead_letter', 'cancelled') then
    raise exception using errcode = '22023', message = 'MEMORY_INVALID_JOB_OUTCOME';
  end if;

  select *
  into job
  from public.memory_jobs
  where id = p_job_id
    and status = 'leased'
    and worker_id = p_worker_id
    and lease_token = p_lease_token
    and lease_expires_at > clock_timestamp()
  for update;

  if not found then
    raise exception using errcode = 'P0001', message = 'MEMORY_STALE_JOB_LEASE';
  end if;

  attempt_started_at := greatest(
    job.lease_started_at,
    least(coalesce(p_started_at, job.lease_started_at), clock_timestamp())
  );

  final_outcome := case
    when p_outcome = 'retryable' and job.attempt_count >= job.max_attempts
      then 'dead_letter'
    else p_outcome
  end;

  insert into public.memory_job_attempts (
    owner_id,
    job_id,
    attempt_number,
    lease_token,
    worker_id,
    provider,
    model,
    token_usage,
    status_code,
    schema_version,
    started_at,
    finished_at,
    outcome,
    error_code,
    redacted_diagnostics,
    duration_ms
  ) values (
    job.owner_id,
    job.id,
    job.attempt_count,
    p_lease_token,
    p_worker_id,
    p_provider,
    p_model,
    coalesce(p_token_usage, '{}'::jsonb),
    p_status_code,
    p_schema_version,
    attempt_started_at,
    clock_timestamp(),
    final_outcome,
    p_error_code,
    coalesce(p_redacted_diagnostics, '{}'::jsonb),
    least(
      2147483647,
      greatest(
        0,
        floor(
          extract(epoch from (clock_timestamp() - attempt_started_at)) * 1000
        )
      )
    )::integer
  );

  update public.memory_jobs
  set status = final_outcome,
      available_at = case
        when final_outcome = 'retryable'
          then clock_timestamp() + make_interval(
            secs => greatest(
              15,
              least(coalesce(p_retry_delay_seconds, 15), 3600)
            )
          )
        else available_at
      end,
      completed_at = case
        when final_outcome in ('succeeded', 'dead_letter', 'cancelled')
          then clock_timestamp()
        else null
      end,
      last_error_code = p_error_code,
      worker_id = null,
      lease_token = null,
      lease_started_at = null,
      lease_expires_at = null,
      updated_at = clock_timestamp()
  where id = job.id
  returning * into job;

  return job;
end;
$$;

create or replace function public.memory_begin_import(
  p_deployment_id text,
  p_writer_epoch bigint,
  p_writer_lease_id uuid,
  p_writer_lease_token text,
  p_source_credential_fingerprint text,
  p_owner_id uuid,
  p_manifest_id text,
  p_contract_version integer,
  p_source_count integer,
  p_message_count integer,
  p_source_hash text
) returns public.memory_import_manifests
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.memory_import_manifests%rowtype;
begin
  perform public.memory_assert_writer(
    p_deployment_id,
    p_writer_epoch,
    p_writer_lease_id,
    p_writer_lease_token,
    p_source_credential_fingerprint
  );

  insert into public.memory_import_manifests (
    owner_id,
    id,
    contract_version,
    source_count,
    message_count,
    source_hash,
    status
  ) values (
    p_owner_id,
    p_manifest_id,
    p_contract_version,
    p_source_count,
    p_message_count,
    p_source_hash,
    'created'
  )
  on conflict (owner_id, id)
  do nothing
  returning * into result;

  if not found then
    select *
    into result
    from public.memory_import_manifests
    where owner_id = p_owner_id
      and id = p_manifest_id
    for update;

    if not found
        or result.contract_version is distinct from p_contract_version
        or result.source_count is distinct from p_source_count
        or result.message_count is distinct from p_message_count
        or result.source_hash is distinct from p_source_hash then
      raise exception using
        errcode = 'PT409',
        message = 'MEMORY_IDEMPOTENCY_CONFLICT';
    end if;
  end if;

  return result;
end;
$$;

create or replace function public.memory_accept_import_chunk(
  p_deployment_id text,
  p_writer_epoch bigint,
  p_writer_lease_id uuid,
  p_writer_lease_token text,
  p_source_credential_fingerprint text,
  p_owner_id uuid,
  p_manifest_id text,
  p_chunk_index integer,
  p_idempotency_key text,
  p_item_count integer,
  p_chunk_hash text,
  p_highest_client_sequence bigint,
  p_highest_client_event_id text,
  p_source_kind text,
  p_observed_at timestamptz
) returns public.memory_import_chunks
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.memory_import_chunks%rowtype;
  watermark public.memory_source_watermarks%rowtype;
  matching_rows bigint;
  matching_id bigint;
begin
  perform public.memory_assert_writer(
    p_deployment_id,
    p_writer_epoch,
    p_writer_lease_id,
    p_writer_lease_token,
    p_source_credential_fingerprint
  );

  insert into public.memory_import_chunks (
    owner_id,
    manifest_id,
    chunk_index,
    idempotency_key,
    item_count,
    chunk_hash,
    source_kind,
    highest_client_sequence,
    highest_client_event_id,
    observed_at,
    status
  ) values (
    p_owner_id,
    p_manifest_id,
    p_chunk_index,
    p_idempotency_key,
    p_item_count,
    p_chunk_hash,
    p_source_kind,
    p_highest_client_sequence,
    p_highest_client_event_id,
    p_observed_at,
    'accepted'
  )
  on conflict do nothing
  returning * into result;

  if not found then
    select count(*), min(id)
    into matching_rows, matching_id
    from public.memory_import_chunks
    where owner_id = p_owner_id
      and (
        idempotency_key = p_idempotency_key
        or (manifest_id = p_manifest_id and chunk_index = p_chunk_index)
      );

    if matching_rows <> 1 then
      raise exception using
        errcode = 'PT409',
        message = 'MEMORY_IDEMPOTENCY_CONFLICT';
    end if;

    select *
    into result
    from public.memory_import_chunks
    where owner_id = p_owner_id
      and id = matching_id
    for update;

    if result.manifest_id is distinct from p_manifest_id
        or result.chunk_index is distinct from p_chunk_index
        or result.idempotency_key is distinct from p_idempotency_key
        or result.item_count is distinct from p_item_count
        or result.chunk_hash is distinct from p_chunk_hash
        or result.source_kind is distinct from p_source_kind
        or result.highest_client_sequence
          is distinct from p_highest_client_sequence
        or result.highest_client_event_id
          is distinct from p_highest_client_event_id
        or result.observed_at is distinct from p_observed_at then
      raise exception using
        errcode = 'PT409',
        message = 'MEMORY_IDEMPOTENCY_CONFLICT';
    end if;
  end if;

  insert into public.memory_source_watermarks (
    owner_id,
    source_kind,
    highest_client_sequence,
    highest_client_event_id,
    observed_at
  ) values (
    result.owner_id,
    result.source_kind,
    result.highest_client_sequence,
    result.highest_client_event_id,
    result.observed_at
  )
  on conflict (owner_id, source_kind)
  do nothing
  returning * into watermark;

  if not found then
    select *
    into watermark
    from public.memory_source_watermarks
    where owner_id = result.owner_id
      and source_kind = result.source_kind
    for update;

    if result.highest_client_sequence = watermark.highest_client_sequence
        and result.highest_client_event_id
          is distinct from watermark.highest_client_event_id then
      raise exception using
        errcode = 'PT409',
        message = 'MEMORY_SOURCE_WATERMARK_CONFLICT';
    elsif result.highest_client_sequence > watermark.highest_client_sequence then
      update public.memory_source_watermarks
      set highest_client_sequence = result.highest_client_sequence,
          highest_client_event_id = result.highest_client_event_id,
          observed_at = result.observed_at,
          updated_at = clock_timestamp()
      where owner_id = result.owner_id
        and source_kind = result.source_kind;
    elsif result.highest_client_sequence = watermark.highest_client_sequence then
      update public.memory_source_watermarks
      set observed_at = greatest(observed_at, result.observed_at),
          updated_at = clock_timestamp()
      where owner_id = result.owner_id
        and source_kind = result.source_kind;
    end if;
  end if;

  return result;
end;
$$;

create or replace function public.memory_record_deletion(
  p_deployment_id text,
  p_writer_epoch bigint,
  p_writer_lease_id uuid,
  p_writer_lease_token text,
  p_source_credential_fingerprint text,
  p_owner_id uuid,
  p_source_kind text,
  p_source_id text,
  p_source_revision integer,
  p_client_event_id text,
  p_deleted_at timestamptz,
  p_reason_code text
) returns public.memory_deletion_ledger
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.memory_deletion_ledger%rowtype;
  matching_rows bigint;
begin
  perform public.memory_assert_writer(
    p_deployment_id,
    p_writer_epoch,
    p_writer_lease_id,
    p_writer_lease_token,
    p_source_credential_fingerprint
  );

  insert into public.memory_deletion_ledger (
    owner_id,
    source_kind,
    source_id,
    source_revision,
    client_event_id,
    deleted_at,
    reason_code
  ) values (
    p_owner_id,
    p_source_kind,
    p_source_id,
    p_source_revision,
    p_client_event_id,
    p_deleted_at,
    p_reason_code
  )
  on conflict do nothing
  returning * into result;

  if not found then
    select count(*)
    into matching_rows
    from public.memory_deletion_ledger
    where owner_id = p_owner_id
      and (
        client_event_id = p_client_event_id
        or (
          source_kind = p_source_kind
          and source_id = p_source_id
          and source_revision = p_source_revision
        )
      );

    if matching_rows <> 1 then
      raise exception using
        errcode = 'PT409',
        message = 'MEMORY_IDEMPOTENCY_CONFLICT';
    end if;

    select *
    into result
    from public.memory_deletion_ledger
    where owner_id = p_owner_id
      and (
        client_event_id = p_client_event_id
        or (
          source_kind = p_source_kind
          and source_id = p_source_id
          and source_revision = p_source_revision
        )
      )
    for update;

    if result.source_kind is distinct from p_source_kind
        or result.source_id is distinct from p_source_id
        or result.source_revision is distinct from p_source_revision
        or result.client_event_id is distinct from p_client_event_id
        or result.deleted_at is distinct from p_deleted_at
        or result.reason_code is distinct from p_reason_code then
      raise exception using
        errcode = 'PT409',
        message = 'MEMORY_IDEMPOTENCY_CONFLICT';
    end if;
  end if;

  perform public.memory_enqueue_job(
    p_deployment_id,
    p_writer_epoch,
    p_writer_lease_id,
    p_writer_lease_token,
    p_source_credential_fingerprint,
    p_owner_id,
    'verify_deletion',
    'deletion:' || p_client_event_id,
    p_source_revision::text,
    jsonb_build_object(
      'sourceKind', p_source_kind,
      'sourceId', p_source_id,
      'sourceRevision', p_source_revision,
      'deletionEventId', p_client_event_id
    ),
    10,
    5
  );

  return result;
end;
$$;

create or replace function public.memory_get_bootstrap()
returns table (
  deployment_id text,
  writer_epoch bigint,
  mode text,
  backend_base_url text,
  database_fingerprint text,
  writer_lease_id uuid,
  writer_lease_expires_at timestamptz,
  writer_lease_issuer text,
  writer_lease_key_id text,
  source_credential_fingerprint text
)
language sql
security definer
set search_path = ''
as $$
  select
    deployment_id,
    writer_epoch,
    mode,
    backend_base_url,
    database_fingerprint,
    writer_lease_id,
    writer_lease_expires_at,
    writer_lease_issuer,
    writer_lease_key_id,
    source_credential_fingerprint
  from public.memory_deployment_authority
  where singleton = true
$$;

create or replace function public.memory_get_owner_state(p_owner_id uuid)
returns setof public.memory_owner_state
language sql
security definer
set search_path = ''
as $$
  select *
  from public.memory_owner_state
  where owner_id = p_owner_id
$$;

create or replace function public.memory_get_source_inventory(p_owner_id uuid)
returns table (
  conversation_count bigint,
  message_count bigint,
  oldest_authored_at timestamptz,
  newest_authored_at timestamptz
)
language sql
security definer
set search_path = ''
as $$
  select
    (
      select count(*)
      from public.memory_conversations
      where owner_id = p_owner_id
    ),
    (
      select count(*)
      from public.memory_messages
      where owner_id = p_owner_id
    ),
    (
      select min(authored_at)
      from public.memory_messages
      where owner_id = p_owner_id
    ),
    (
      select max(authored_at)
      from public.memory_messages
      where owner_id = p_owner_id
    )
$$;

revoke all on function public.memory_assert_writer(
  text,
  bigint,
  uuid,
  text,
  text
) from public;
revoke all on function public.memory_enqueue_job(
  text,
  bigint,
  uuid,
  text,
  text,
  uuid,
  text,
  text,
  text,
  jsonb,
  integer,
  integer
) from public;
revoke all on function public.memory_claim_jobs(
  text,
  bigint,
  uuid,
  text,
  text,
  text,
  integer,
  integer
) from public;
revoke all on function public.memory_finish_job(
  text,
  bigint,
  uuid,
  text,
  text,
  bigint,
  text,
  uuid,
  text,
  text,
  integer,
  text,
  text,
  jsonb,
  integer,
  integer,
  timestamptz,
  jsonb
) from public;
revoke all on function public.memory_begin_import(
  text,
  bigint,
  uuid,
  text,
  text,
  uuid,
  text,
  integer,
  integer,
  integer,
  text
) from public;
revoke all on function public.memory_accept_import_chunk(
  text,
  bigint,
  uuid,
  text,
  text,
  uuid,
  text,
  integer,
  text,
  integer,
  text,
  bigint,
  text,
  text,
  timestamptz
) from public;
revoke all on function public.memory_record_deletion(
  text,
  bigint,
  uuid,
  text,
  text,
  uuid,
  text,
  text,
  integer,
  text,
  timestamptz,
  text
) from public;
revoke all on function public.memory_get_bootstrap() from public;
revoke all on function public.memory_get_owner_state(uuid) from public;
revoke all on function public.memory_get_source_inventory(uuid) from public;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'memory_owner_state', 'memory_source_watermarks', 'memory_deletion_ledger',
    'memory_conversations', 'memory_messages',
    'memory_message_revisions', 'memory_evidence_spans',
    'memory_import_manifests', 'memory_import_chunks',
    'memory_jobs', 'memory_job_attempts', 'turn_traces'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('alter table public.%I force row level security', table_name);
    execute format(
      'create policy %I on public.%I for all to authenticated '
      || 'using ((select auth.uid()) = owner_id) '
      || 'with check ((select auth.uid()) = owner_id)',
      table_name || '_owner_access',
      table_name
    );
  end loop;
end
$$;

alter table public.memory_deployment_authority enable row level security;
alter table public.memory_deployment_authority force row level security;

revoke all on table
  public.memory_deployment_authority,
  public.memory_owner_state,
  public.memory_source_watermarks,
  public.memory_deletion_ledger,
  public.memory_conversations,
  public.memory_messages,
  public.memory_message_revisions,
  public.memory_evidence_spans,
  public.memory_import_manifests,
  public.memory_import_chunks,
  public.memory_jobs,
  public.memory_job_attempts,
  public.turn_traces
from public, anon, authenticated, service_role;

grant select on table
  public.memory_owner_state,
  public.memory_source_watermarks,
  public.memory_deletion_ledger,
  public.memory_conversations,
  public.memory_messages
to authenticated;

revoke all on function public.memory_assert_writer(text, bigint, uuid, text, text)
  from public, anon, authenticated, service_role;
revoke all on function public.memory_enqueue_job(
  text, bigint, uuid, text, text, uuid, text, text, text, jsonb, integer, integer
) from public, anon, authenticated;
revoke all on function public.memory_claim_jobs(
  text, bigint, uuid, text, text, text, integer, integer
)
  from public, anon, authenticated;
revoke all on function public.memory_finish_job(
  text, bigint, uuid, text, text, bigint, text, uuid, text, text, integer,
  text, text, jsonb, integer, integer, timestamptz, jsonb
) from public, anon, authenticated;
revoke all on function public.memory_begin_import(
  text, bigint, uuid, text, text, uuid, text, integer, integer, integer, text
) from public, anon, authenticated;
revoke all on function public.memory_accept_import_chunk(
  text, bigint, uuid, text, text, uuid, text, integer, text, integer, text,
  bigint, text, text, timestamptz
) from public, anon, authenticated;
revoke all on function public.memory_record_deletion(
  text, bigint, uuid, text, text, uuid, text, text, integer, text,
  timestamptz, text
) from public, anon, authenticated;
revoke all on function public.memory_get_bootstrap()
  from public, anon, authenticated;
revoke all on function public.memory_get_owner_state(uuid)
  from public, anon, authenticated;
revoke all on function public.memory_get_source_inventory(uuid)
  from public, anon, authenticated;

grant execute on function public.memory_enqueue_job(
  text, bigint, uuid, text, text, uuid, text, text, text, jsonb, integer, integer
) to service_role;
grant execute on function public.memory_claim_jobs(
  text, bigint, uuid, text, text, text, integer, integer
)
  to service_role;
grant execute on function public.memory_finish_job(
  text, bigint, uuid, text, text, bigint, text, uuid, text, text, integer,
  text, text, jsonb, integer, integer, timestamptz, jsonb
) to service_role;
grant execute on function public.memory_begin_import(
  text, bigint, uuid, text, text, uuid, text, integer, integer, integer, text
) to service_role;
grant execute on function public.memory_accept_import_chunk(
  text, bigint, uuid, text, text, uuid, text, integer, text, integer, text,
  bigint, text, text, timestamptz
) to service_role;
grant execute on function public.memory_record_deletion(
  text, bigint, uuid, text, text, uuid, text, text, integer, text,
  timestamptz, text
) to service_role;
grant execute on function public.memory_get_bootstrap() to service_role;
grant execute on function public.memory_get_owner_state(uuid) to service_role;
grant execute on function public.memory_get_source_inventory(uuid) to service_role;
